import {readFile, writeFile, mkdir, cp, rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve, dirname} from 'node:path';
export const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export async function engineSource(){
  const files=await Promise.all(['config.js','engine.js'].map(name=>readFile(resolve(root,'src',name),'utf8')));
  return files.join('\n').replace(/^import .*;\n/gm,'').replace(/^export /gm,'');
}
export async function build(){
  await writeFile(resolve(root,'web/runtime-source.js'),`// Generated by npm run build. Do not edit manually.\nexport const ENGINE_SOURCE = ${JSON.stringify(await engineSource())};\n`);
  await rm(resolve(root,'dist'),{recursive:true,force:true});
  await mkdir(resolve(root,'dist'),{recursive:true});
  for(const dir of ['src','web'])await cp(resolve(root,dir),resolve(root,'dist',dir),{recursive:true});
  await cp(resolve(root,'web/index.html'),resolve(root,'dist/index.html'));
  const [page, css, player, app] = await Promise.all(['web/index.html','web/style.css','src/player.js','web/app.js'].map(path=>readFile(resolve(root,path),'utf8')));
  const source = await engineSource();
  const module = source + '\n' + player.replace(/^import .*;\n/gm,'').replace(/^export /gm,'') + '\nconst ENGINE_SOURCE = ' + JSON.stringify(source) + ';\n' + app.replace(/^import .*;\n/gm,'');
  const standalone = page.replace('<link rel="stylesheet" href="/web/style.css">', '<style>'+css+'</style>').replace('<script type="module" src="/web/app.js"></script>', () => '<script type="module">'+module.replaceAll('</script','<\\/script')+'</script>');
  await writeFile(resolve(root,'studio.html'),standalone);
  await writeFile(resolve(root,'dist/studio.html'),standalone);
  console.log('Built dist/ and studio.html (standalone offline editor).');
}
if(process.argv[1] && resolve(process.argv[1])===fileURLToPath(import.meta.url))await build();
